### ISSUE TITLE
Multi-core processing

### ISSUE THREAD

**Issue by Sappharad** [Sappharad/mp3gainOSX#10]
I received a request for multi-core processing, so that multiple tracks can be processed at once more quickly.

I don't think this should be too difficult, I'm already spawning off a separate thread to keep the UI responsive, so it might be feasible to spawn off a few more.

This feature has been requested twice.

**Comment by Sappharad** [comment]
Added in 05ed8d73ab206d093d3b141d150d82ac0c737148
This issue will be closed when 2.0 is released.

**Comment by HendrikBoone** [comment]
Well done, will soon report some testing results here.

**Comment by Sappharad** [comment]
The biggest thing I was worried about was stuff not processing at all and getting stuck at 0%, so that part working is good news.

Didn't run into any volume problems during my testing. Did you use the exact same settings as the old build? The new album mode checkbox should almost never be used, because it causes all tracks in your list to be treated as a single track so the maximum volume is changed relative to the loudest track in your list and not individual tracks.
