### ISSUE TITLE
Possible to have command line option that matches the target decibels option in the GUI?

### ISSUE THREAD

**Issue by technicaltitch** [Sappharad/mp3gainOSX#29]
I am trying to use the command line version of mp3gainOSX in the same way I use the GUI.

I want to set a target "Normal" dB of 92.

The `-d` option seems the closest but I'm not sure how exactly. An alternative might be documentation on how the GUI option relates to the vanilla mp3gain option? 

Looking at `file.volume = desiredDb - gain`, is the default of mp3gain 89, so `-d` equivalent is simply `+3`? This seems not to come up with the same result when I compare CLI with GUI.

(Enormous thanks for a very treasured tool.)

**Comment by Sappharad** [comment]
Just a reminder that I didn't write the original command line app, I'm just providing a build of it. You are correct, -d 3.0 would normalize to 92.

MP3Gain Express passes -r -k -d NUMBER if no clipping is enabled, and -r -c -d NUMBER if clipping is allowed. Where NUMBER is (desiredDb-89.0)

Replace -r with -a for album gain across multiple tracks at once.

**Comment by technicaltitch** [comment]
Huge thanks that's really helpful - my collection is levelled with your GUI build so I wanted to match that. Thanks again.
