### ISSUE TITLE
Feature request: Add compatibility with WAV files-

### ISSUE THREAD

**Issue by Petrus125** [Sappharad/mp3gainOSX#36]
Would be posible to add WAV files compatible? would be great indeed.

**Comment by Sappharad** [comment]
No, sorry. The point of MP3Gain is to make reversible modifications to the file. You can't change the volume of a WAV file without altering the original audio data.
Also this uses a fork of the original MP3Gain, I'm not interested in adding the kind of features here that belong in the original code.

If you want to alter the volume of a WAV file you can use a tool like Audacity. You can use the Macros feature in Audacity to set up a series of steps that can be applied to multiple files.
